### ISSUE TITLE
Markdown "Tender comments" not as intended

### ISSUE THREAD

**Issue by FrankvanMourik** [Inter-Actief/alexia#104]
It would be nice to add some type of markdown to the "Tender comments" section of an activity.
Example entry field:
![image](https://user-images.githubusercontent.com/15890909/190367293-355b85a8-d472-4ff3-8a1b-c6ac1496192e.png)
Current implementation:
![image](https://user-images.githubusercontent.com/15890909/190368181-18023365-3e20-4954-a72c-e7a31f6b6b82.png)
Proposed implementation:
![image](https://user-images.githubusercontent.com/15890909/190367111-48a89a8a-405c-4083-8823-41054b920d24.png)

**Comment by bramvandartel** [comment]
I think the main issue is not the markdown, but the linebreaks. Will fix that, as that is the easiest to fix and should fix the issue equally well.
