### ISSUE TITLE
Only count drinks with DCF or transactions towards "tended drinks"

### ISSUE THREAD

**Issue by FrankvanMourik** [Inter-Actief/alexia#108]
As Inter-_Actief_ will use the Alexia "tended drinks" for their bartenders' appreciation policy, it would be nice to have the tended drinks as a better representation of exactly how many drinks a bartender has tended.

To have a better indication, we propose the following additional constraint on the query: **only count drinks that have either a digital consumption form filled out or have at least one transaction linked with them**.  By taking this constraint into account, drinks like "Bartenders' outing [inventarisation]" or "TIPcie & SBZ trekken bak" will not be taken into account.

Furthermore, we believe that this would not negatively impact other associations in any way.

**Comment by CasEbb** [comment]
Bear in mind that this comes at the expense of the accuracy of the historical data. Consumption forms or Juliana transactions were not in use before 2012, which would mean that for former bartenders, their counter either goes down drastically or goes to zero.

This may lead to a violation of honour.

**Comment by FrankvanMourik** [comment]
@CasEbb your statement is taken into account by adding an OR filter on drinks before the date of the first DCF (December 13th, 2016)

**Comment by CasEbb** [comment]
On behalf of the oude lullen of this world, 'vo.
