### ISSUE TITLE
Option "wegboeken"

### ISSUE THREAD

**Issue by barryth** [Inter-Actief/alexia#118]
For being able to process and count which drinks are given away for free, we would like a "wegboeken" option in the Point of Sale. 
This option does not process the drinks that are selected to an account, but to a separate post.
The idea is that afterwards, in the "/billing/orders/" tab of an activity, it would be nice to have a separate table with all the orders that have been processed with this option.

**Comment by WKobes** [comment]
Related to #55

**Comment by Kurocon** [comment]
I have some ideas where we might be able to add multiple types of "wegboek" posts, so you could have a separate overview for bartender drinks, ERO drinks and cleaning drinks for example. (And cash, if we still want to add that...)

**Comment by SimplyPancake** [comment]
"Write off" (wegboeken) implementation notes:

If organisation has _write off_ feature enabled, cash button on POS will turn into "write off"  button, which will redirect to a new screen where a write-off category can be selected.

*writeoff* many-1 table:
- Name
- Short description
- Color
- Id

new type of order model that does not synchronise with a payment system (+purchase model)

writeoff-view per drink + orders per writeoff-category + splitted-out view of written off orders

**Comment by SimplyPancake** [comment]
Additional features request from someone: add a JSON export to the written off overview
