### ISSUE TITLE
Comments availibility

### ISSUE THREAD

**Issue by maasrf** [Inter-Actief/alexia#120]
Right now, when a bartender fills in their availibility they can only choose from the availible options. As most of the times the shifts are quite long it happens quite often that someone would be able to or willing to tend a partial drink during certain times, or that they can tend but cannot build the drink for example.

We would like there to be a small comment field for the bartenders filling in their availibility next to the drop-down where they can specify things like this.

**Comment by Michael-Janssen-dev** [comment]
This would involve:
* Adding a 'comment' field to BartenderAvailability, null and blank allowed

Updating the following screens:
* Home: adding a comment icon with a popup to add a comment (`alert` would work fine, I believe Alexia doesn't have modals). Should only be visible if availability is already set.
* Event details: adding a comment icon with a tooltip displaying the comment for schedulers
* Availability matrix: same thing

I think this can be applied to all organizations, and not require a flag per organization.
