### ISSUE TITLE
Postgresql is not supported

### ISSUE THREAD

**Issue by cmitz** [Inter-Actief/alexia#47]
I've tried to get Alexia running with a postgres database, but not all migrations have valid postgres syntax. For example: https://github.com/Inter-Actief/alexia/blob/master/alexia/apps/billing/migrations/0014_auto_20170116_1927.py

This migration contains a sql query that didn't work on my machine (that has postgres running instead of mysql).

I've just installed MySQL and everything worked like a charm. I'm still reporting this, you might want to remove postgresql from the list of possibly supported db's ;)

**Comment by CasEbbers** [comment]
Unfortunately Postgres and MySQL have different UPDATE syntaxes when it comes to joins. Since our production environments use MySQL, there won't be any Postgres support.
