### ISSUE TITLE
Adjust price after activity

### ISSUE THREAD

**Issue by Floormidabel** [Inter-Actief/alexia#52]
Scintilla has the habit of putting a "max prize" on activities, meaning that the price of an activity can be lowered after the activity when costs end up less than predicted. For the EEMCS firstyears activity this has also been settled as the financial construction, so it has to be possible for the board to adjust the price down. This is also useful for merchandise for example, since this can become cheaper a piece when more are ordered.

**Comment by Floormidabel** [comment]
it should not be possible to adjust the price upwards of course

**Comment by Kurocon** [comment]
I think this is probably supposed to be a [Inter-Actief/amelie](https://github.com/Inter-Actief/amelie/) issue rather than an Alexia issue?
