### ISSUE TITLE
Make a user's first_name, last_name and nickname editable for the user

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/alexia#60]
To comply with the GDPR, data should be as much in control of the end-user as possible. Therefore I think it should be possible for every user to change their name as they have submitted during the initial login, as well as the nickname that they optionally have been given.

**Comment by CasEbbers** [comment]
Regarding first- and last name: a great portion of the data (like 95%) is supplied by the associations, and therefore they should contact their primary association to correct their data. We should however, look at some way for the associations to keep the data in sync.

Regarding bartender nicknames: it's not desirable for users to edit their own bartender nickname, keeping abusement in regard. They are however always free to contact managers of their association to request an amendment of their nickname.

Personal thoughts btw: feel free to discuss.

**Comment by WKobes** [comment]
Information is managed by associations. Information can be requested, and altered on request. Nicknames are already discussed in another ticket.

No priority to adding this any time soon. wontfix.
