### ISSUE TITLE
Move nickname to profile edit form or make it membership dependable

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/alexia#61]
Currently the nickname can be changed in the Membership form. In theory, a person can be a tender at multiple organisations, which causes that other associations could edit the same nickname field. In my opinion this field should be either moved to the ProfileEditForm, or the 'nickname' field should be made Membership-specific.

**Comment by CasEbbers** [comment]
Yeah, I agree. 7ed97487ae4 was a quick fix and the nickname should definitely be a property of the Membership model. Will be working on that.

**Comment by WKobes** [comment]
Low priority in current development progress
