### ISSUE TITLE
Actual tender comments in popup

### ISSUE THREAD

**Issue by jochemschutte** [Inter-Actief/alexia#67]
If one hovers over the 'I' signifying that a drink has tender comments, the popup reads "Has tender comments" (&lt;sarcasm&gt;how fucking usefull&lt;/sarcasm&gt;). Why not put the actual tender comment into the popup?

Proposal1
Just put the tender comment in the title field.

Proposal2
Do a permission/association check. If the user is allowed to watch the tender comments (in accordance with its associations and permissions), then put the tender comments into the title field, (possibly prepended by "Tender comment: ". If not, put the text "Has tender comments" into the title field.
This proposal is based on the pesupposition that a tepper is only allowed to see tender comments of its own association (not checked). If this is not true, refer back to Proposal1.

**Comment by niomaster** [comment]
Problem is here: https://github.com/Inter-Actief/alexia/blob/master/templates/scheduling/event_list.html#L76-L80

I would suggest a similar fix for the annotation next to digital consumption forms, "Has Comments", here: https://github.com/Inter-Actief/alexia/blob/master/templates/consumption/consumptionform_list.html#L95-L99

**Comment by niomaster** [comment]
Note that the tender instruction icon is in fact already guarded as in proposal2
