### ISSUE TITLE
Remove the Latest Login column from the Users overview

### ISSUE THREAD

**Issue by Jottee** [Inter-Actief/alexia#79]
There is no real need for anyone with Manager rights to see everyone's last moment of login.

**Comment by WKobes** [comment]
The information is useful to check which tenders already have logged in after a certain event became open for enrollment.  Furthermore, you can generally check how active your bartenders are. For some associations, this is preferable over mandatory status completion of all events.

The information is insensitive, non-identifiable, so from privacy perspective there appears not to be a problem.
